# Generated by Django 4.1.2 on 2022-12-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0004_alter_inventory_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
